// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0v0mim9QdYeV8XPX3lrcf-st9qhChbrs',
    appId: '1:953567384679:web:162f5fdd3fa7d5b6af30c2',
    messagingSenderId: '953567384679',
    projectId: 'friendle-2c8a4',
    authDomain: 'friendle-2c8a4.firebaseapp.com',
    storageBucket: 'friendle-2c8a4.firebasestorage.app',
    measurementId: 'G-6RY8S2V16K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJjHqCHDsxKiRvCyvhAZKbkro_33WHZs',
    appId: '1:953567384679:android:2c8c0a3b1727e1bfaf30c2',
    messagingSenderId: '953567384679',
    projectId: 'friendle-2c8a4',
    storageBucket: 'friendle-2c8a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjb4WvLBoDOzn90abi5c9SqMfjDMCyZy0',
    appId: '1:953567384679:ios:a78e579207c2f0c3af30c2',
    messagingSenderId: '953567384679',
    projectId: 'friendle-2c8a4',
    storageBucket: 'friendle-2c8a4.firebasestorage.app',
    iosBundleId: 'com.example.friendle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjb4WvLBoDOzn90abi5c9SqMfjDMCyZy0',
    appId: '1:953567384679:ios:a78e579207c2f0c3af30c2',
    messagingSenderId: '953567384679',
    projectId: 'friendle-2c8a4',
    storageBucket: 'friendle-2c8a4.firebasestorage.app',
    iosBundleId: 'com.example.friendle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0v0mim9QdYeV8XPX3lrcf-st9qhChbrs',
    appId: '1:953567384679:web:4ded9977d0696a31af30c2',
    messagingSenderId: '953567384679',
    projectId: 'friendle-2c8a4',
    authDomain: 'friendle-2c8a4.firebaseapp.com',
    storageBucket: 'friendle-2c8a4.firebasestorage.app',
    measurementId: 'G-7Q4292QQBM',
  );
}
